ENDIAN = "little"
FILE_NAME = "myport.info"
CLIENT_ID_SIZE = 16
VERSION_SIZE = 1
CODE_SIZE = 2
PAYLOAD_SZ_SIZE = 4
USERNAME_LENGTH = 254
DATABASE_NAME = "defensive.db"
REGISTER_CODE = 600
CLIENTS_LIST_CODE = 601
CLIENT_PUB_KEY_CODE = 602
SEND_MSG_CODE = 603
WAITING_MESSAGES_CODE = 604

ERROR_USERNAME_EXISTS = -10
OK = 1

