FILE_NAME = "myport.info"
DATABASE_NAME = "defensive.db"

CLIENT_ID_SIZE = 16
VERSION_SIZE = 1
CODE_SIZE = 2
PAYLOAD_SZ_SIZE = 4
USERNAME_LENGTH = 254
MSG_TYPE_SIZE = 1
CONTENT_SZ_SIZE = 4
MSG_ID_SIZE = 4

REGISTER_CODE = 600
CLIENTS_LIST_CODE = 601
CLIENT_PUB_KEY_CODE = 602
SEND_MSG_CODE = 603
WAITING_MESSAGES_CODE = 604

ERROR_USERNAME_EXISTS = -10
ERROR_CID_NOT_EXISTS = -11
ERROR_NO_WAITING_MSGS = -12

ERROR_SERVER = 9000
OK = 1

